name: Check unit test
on: push

jobs:
  test:
    name: Testing TC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"
      - name: Caching Python
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: tubes-${{ env.pythonLocation }}-${{ hashFiles('main.py') }}-${{ hashFiles('requirements.txt') }}
      - name: Install Depedency
        run: |
          pip install --upgrade --upgrade-strategy eager -r requirements.txt
      - name: Testing
        run: |
          pytest .
